branches:
  only:
    - master
    - v14

language: android
jdk: oraclejdk7
android:
  components:
    - tools
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - android-23
    - build-tools-23.0.1
  licenses:
        - '.+'

before_install:
 - chmod +x gradlew

install:
  - ./gradlew dependencies

script:
  - ./gradlew build
